FROM python:3.7-alpine
WORKDIR /app
RUN apk add --no-cache bash git
ADD ./requirements.txt /app
RUN pip install -r requirements.txt
COPY src /app/src
ADD app.py /app
CMD ["gunicorn", "-b", "0.0.0.0:5441", "app:app"]
